name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: MP4 driver tests
      id: mp4-driver-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: MP4 driver tests
        setup-command: make clean; make
        command: "./longrun.sh"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MP4-DRIVER-TESTS_RESULTS: "${{steps.mp4-driver-tests.outputs.result}}"
      with:
        runners: mp4-driver-tests
